In [5]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\itvedant cr3-08\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\itvedant cr3-08\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\itvedant cr3-08\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --------- ------------------------------ 2.4/9.7 MB 11.7 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.7 MB 11.7 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.7 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 10.9 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
print(pd.__version__)

3.0.1

In [7]:
# pd.series()
data = ["java","c++","python","go","jsp","ruby","r"]

for i in range(len(data)):
    print(i,data[i])

0 java
1 c++
2 python
3 go
4 jsp
5 ruby
6 r

In [8]:
#using pandas series()
s = pd.Series(data)
print(s)

0      java
1       c++
2    python
3        go
4       jsp
5      ruby
6         r
dtype: str

In [9]:
# using index
indexx = [101,102,103,104,105,106,107]
s = pd.Series(data,index=indexx)
print(s)

101      java
102       c++
103    python
104        go
105       jsp
106      ruby
107         r
dtype: str

In [10]:
data = {
    "name":["rupali","disha","rahasya","shreya","akhilesh","prajwal"],
    "age":[22,23,24,25,26,27],
    "city":["mumbai","gujrat","banglore","pune","nandura","amravati"]
}

In [11]:
indexx = [101,102,103,104,105,106]
#pd.DataFrame()
df = pd.DataFrame(data,index=indexx)
df

         name  age      city
101    rupali   22    mumbai
102     disha   23    gujrat
103   rahasya   24  banglore
104    shreya   25      pune
105  akhilesh   26   nandura
106   prajwal   27  amravati

In [12]:
#export file
df.to_csv("data1.csv")

In [ ]:
##export file without index
df.to_csv("data1.csv",index=False)

In [20]:
# load data from folder
#data = pd.read_csv("ecommerce_data.csv")
# load online row file
data = pd.read_csv("https://raw.githubusercontent.com/Pankaj-Str/Complete-Python-Mastery/refs/heads/main/53%20DataSet/ecommerce_data.csv")
print(data)

     Order ID     Product     Category  Quantity Ordered  Price Each  \
0           1      Laptop  Electronics                 1      834.18
1           2       Shoes      Apparel                 4      903.27
2           3      Laptop  Electronics                 2      365.51
3           4      Pillow   Home Goods                 5      169.17
4           5  Smartphone  Electronics                 5      498.51
..        ...         ...          ...               ...         ...
995       996      Pillow   Home Goods                 2      752.76
996       997       Shoes      Apparel                 5      787.67
997       998  Coffee Mug   Home Goods                 1      718.24
998       999     Blanket   Home Goods                 5      650.08
999      1000         Hat      Apparel                 3       71.90

              Order Date       City  Customer ID
0    2024-07-28 15:26:51    Chicago         4676
1    2024-01-26 13:10:16   New York         1891
2    2024-12-02 20:36:02    Chicago         4254
3    2024-04-27 02:18:27    Houston         2859
4    2024-03-31 06:02:42    Phoenix         5713
..                   ...        ...          ...
995  2024-06-26 09:37:10   New York         3617
996  2024-07-13 13:31:12     Dallas         3102
997  2024-06-04 04:07:58     Dallas         1024
998  2024-11-09 19:25:05   New York         9758
999  2024-04-09 23:07:43  San Diego         3170

[1000 rows x 8 columns]

In [21]:
data.head(5) #load 5 row

,Order ID,Product,Category,Quantity Ordered,Price Each,Order Date,City,Customer ID
0,1,Laptop,Electronics,1,834.18,2024-07-28 15:26:51,Chicago,4676
1,2,Shoes,Apparel,4,903.27,2024-01-26 13:10:16,New York,1891
2,3,Laptop,Electronics,2,365.51,2024-12-02 20:36:02,Chicago,4254
3,4,Pillow,Home Goods,5,169.17,2024-04-27 02:18:27,Houston,2859
4,5,Smartphone,Electronics,5,498.51,2024-03-31 06:02:42,Phoenix,5713

In [22]:
#tail(5) last 5 row
data.tail(5)

,Order ID,Product,Category,Quantity Ordered,Price Each,Order Date,City,Customer ID
995,996,Pillow,Home Goods,2,752.76,2024-06-26 09:37:10,New York,3617
996,997,Shoes,Apparel,5,787.67,2024-07-13 13:31:12,Dallas,3102
997,998,Coffee Mug,Home Goods,1,718.24,2024-06-04 04:07:58,Dallas,1024
998,999,Blanket,Home Goods,5,650.08,2024-11-09 19:25:05,New York,9758
999,1000,Hat,Apparel,3,71.90,2024-04-09 23:07:43,San Diego,3170

In [23]:
#show info
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          1000 non-null   int64
 1   Product           1000 non-null   str
 2   Category          1000 non-null   str
 3   Quantity Ordered  1000 non-null   int64
 4   Price Each        1000 non-null   float64
 5   Order Date        1000 non-null   str
 6   City              1000 non-null   str
 7   Customer ID       1000 non-null   int64
dtypes: float64(1), int64(3), str(4)
memory usage: 62.6 KB

In [24]:
data.shape #find raw column number

(1000, 8)

In [26]:
#print column name
print(data.columns.to_list())

['Order ID', 'Product', 'Category', 'Quantity Ordered', 'Price Each', 'Order Date', 'City', 'Customer ID']

In [27]:
print(data.describe())

          Order ID  Quantity Ordered   Price Each  Customer ID
count  1000.000000       1000.000000  1000.000000  1000.000000
mean    500.500000          3.042000   512.290660  5353.868000
std     288.819436          1.415712   287.656557  2551.056437
min       1.000000          1.000000     5.150000  1004.000000
25%     250.750000          2.000000   264.067500  3222.500000
50%     500.500000          3.000000   513.210000  5356.500000
75%     750.250000          4.000000   770.720000  7463.500000
max    1000.000000          5.000000   999.860000  9982.000000

In [28]:
print(data.dtypes)

Order ID              int64
Product                 str
Category                str
Quantity Ordered      int64
Price Each          float64
Order Date              str
City                    str
Customer ID           int64
dtype: object